# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

 # Clean and increment build
  before_all do
    increment_build_number
  end

  # Run Unit tests and UI tests
  lane :tests do
  		run_tests(scheme: "GithubStarsTests")
      run_tests(scheme: "GithubStarsUITests")
	end

  # Beta version
	lane :beta do

  # Apply the badge "beta" on the icon app
  add_badge(shield: "Version 1.0.0-blue", dark: true)

	# Build the app
  gym(
    workspace: "GithubStars.xcworkspace",
    configuration: "Beta",
    scheme: "GithubStars",
    export_method: 'ad-hoc',
    clean: true
  )

  # Upload the build to HockeyApp
  hockey(
    api_token: ENV["HOCKEY_API_TOKEN"],
    public_identifier: ENV["HOCKEY_APP_PUBLIC_IDENTIFIER"],
    notify: '1'
  )

end
end
